import type { Button } from "@/types";

export interface Intent {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  trainingExamples: string[];
  templateResponse: {
    text: string;
    buttons: Button[];
  };
}

export interface OutOfScopeIntent {
  id: string;
  name: string;
  templateResponse: {
    text: string;
    buttons: Button[];
  };
}


export const CREDIT_CARD_INTENTS: Intent[] = [
  {
    id: "discover_best_credit_card",
    name: "Discover Best Overall Credit Card",
    description:
      "Help customer identify a suitable all-rounder OCBC credit card based on general spending with no strong category preference.",
    keywords: [
      "best",
      "everyday",
      "versatile",
      "all-round",
      "allrounder",
      "general",
      "overall",
      "spending",
      "recommend",
      "credit",
      "card",
      "suitable",
      "good",
    ],
    trainingExamples: [
      "What is the best OCBC credit card for everyday use?",
      "Which OCBC card is the most versatile?",
      "Suggest a good all-round OCBC credit card.",
      "What credit card should I get?",
      "Best credit card for general spending",
      "Recommend me a credit card",
    ],
    templateResponse: {
      text: "Here are OCBC credit cards that work well for everyday spend (cashback, miles and rewards). Tap **Apply Cards** below to compare and start.",
      buttons: [{ label: "View All Credit Cards", url: "https://www.ocbc.com/personal-banking/cards/credit-card" }],
    },
  },
  {
    id: "dining_restaurants",
    name: "Dining & Restaurants",
    description:
      "Identify OCBC credit cards optimized for local and overseas dining, cafes, bars.",
    keywords: [
      "dining",
      "restaurant",
      "cafe",
      "cafes",
      "bar",
      "bars",
      "food",
      "eat",
      "eating",
      "dinner",
      "lunch",
      "meal",
      "cashback",
      "dine",
    ],
    trainingExamples: [
      "Which OCBC card is best for dining?",
      "Any OCBC credit card with high cashback for restaurants?",
      "What card should I use for cafes and bars?",
      "Best card for eating out",
      "Dining rewards credit card",
      "Card for restaurant spend",
    ],
    templateResponse: {
      text: "If you dine out often, consider cards that reward restaurants, cafes and bars. Tap **Apply Cards** below to see eligible cards and current benefits.",
      buttons: [{ label: "View Dining Cards", url: "https://www.ocbc.com/personal-banking/cards/365-cashback-credit-card" }],
    },
  },
  {
    id: "groceries_supermarkets",
    name: "Groceries & Supermarkets",
    description:
      "Suggest credit cards tailored for supermarket and grocery spending in Singapore (online/offline).",
    keywords: [
      "grocery",
      "groceries",
      "supermarket",
      "fairprice",
      "ntuc",
      "cold",
      "storage",
      "online",
      "shopping",
      "food",
      "household",
      "savings",
    ],
    trainingExamples: [
      "Best OCBC card for groceries?",
      "Which card gives the highest savings at supermarkets?",
      "Online grocery cashback with OCBC?",
      "Best card for supermarket shopping",
      "Grocery cashback card",
      "Card for FairPrice/Cold Storage",
    ],
    templateResponse: {
      text: "For supermarket and grocery runs (online/offline), look for cards with grocery/category cashback. Use the link below to compare and apply.",
      buttons: [{ label: "View Grocery Cards", url: "https://www.ocbc.com/personal-banking/cards/365-cashback-credit-card" }],
    },
  },
  {
    id: "transport_fuel",
    name: "Transport & Fuel",
    description:
      "Identify cards that reward petrol stations, public transport, ride-hailing.",
    keywords: [
      "petrol",
      "fuel",
      "transport",
      "mrt",
      "bus",
      "grab",
      "ride",
      "hailing",
      "taxi",
      "ez-link",
      "commute",
      "driving",
      "car",
      "drive",
    ],
    trainingExamples: [
      "Which OCBC card is best for petrol?",
      "Any card with perks for bus/MRT or Grab?",
      "I drive—what OCBC card should I get?",
      "Best card for transport",
      "Petrol rebate card",
      "Grab cashback card",
      "Card for commuters",
    ],
    templateResponse: {
      text: "Drivers and commuters can save on petrol, ride\u2011hailing and public transport with selected cards. Use the link to view options and apply.",
      buttons: [{ label: "View Transport Cards", url: "https://www.ocbc.com/personal-banking/cards/credit-card" }],
    },
  },
  {
    id: "online_shopping",
    name: "Online Shopping & Marketplaces",
    description:
      "Recommend cards that reward e-commerce and digital wallets (where eligible).",
    keywords: [
      "online",
      "shopping",
      "ecommerce",
      "lazada",
      "shopee",
      "amazon",
      "marketplace",
      "digital",
      "wallet",
      "internet",
      "web",
      "purchase",
    ],
    trainingExamples: [
      "Which OCBC card is best for online shopping?",
      "Any card good for Lazada/Shopee?",
      "Does OCBC give extra for online spend?",
      "Best card for e-commerce",
      "Online cashback card",
      "Card for Shopee/Lazada",
      "Card for digital purchases",
    ],
    templateResponse: {
      text: "If most of your spend is online (e\u2011commerce, marketplaces), browse OCBC cards that boost online transactions and then apply from the catalog.",
      buttons: [{ label: "View Online Shopping Cards", url: "https://www.ocbc.com/personal-banking/cards/titanium-rewards-credit-card" }],
    },
  },
  {
    id: "travel_miles",
    name: "Travel (Air Miles)",
    description:
      "Help users prioritizing miles accumulation for flights and travel-related spend.",
    keywords: [
      "miles",
      "travel",
      "air",
      "flight",
      "krisflyer",
      "aviation",
      "lounge",
      "airport",
      "hotel",
      "booking",
      "overseas",
      "holiday",
      "vacation",
    ],
    trainingExamples: [
      "Which OCBC card earns the most miles?",
      "Best OCBC card for travel bookings?",
      "Any OCBC card with airport lounge access?",
      "Best miles card",
      "Air miles credit card",
      "Card for frequent travellers",
      "KrisFlyer miles card",
    ],
    templateResponse: {
      text: "Prefer earning miles? Browse OCBC air\u2011miles cards, check transfer partners and fees, then apply using the button below.",
      buttons: [{ label: "View Miles Cards", url: "https://www.ocbc.com/personal-banking/cards/90-degrees-travel-credit-card" }],
    },
  },
  {
    id: "cashback",
    name: "Cashback Focus",
    description:
      "Customer prefers cash rebates over points/miles; wants predictable bill savings.",
    keywords: [
      "cashback",
      "rebate",
      "cash",
      "back",
      "rebates",
      "refund",
      "money",
      "back",
      "percentage",
      "percent",
      "monthly",
      "cap",
      "highest",
    ],
    trainingExamples: [
      "What is the best cashback OCBC card?",
      "Which card gives highest monthly cashback?",
      "I want consistent rebate rather than miles",
      "Best cashback card",
      "Highest cashback rate",
      "Cash rebate credit card",
      "Card with highest cashback",
    ],
    templateResponse: {
      text: "If you want predictable bill savings, review OCBC cashback cards (caps and minimum spends apply). Tap through to compare and apply.",
      buttons: [{ label: "View Cashback Cards", url: "https://www.ocbc.com/personal-banking/cards/infinity-unlimited-cashback-card.page" }],
    },
  },
  {
    id: "no_annual_fee",
    name: "No/Low Annual Fee",
    description: "Users looking for cards with waived or low annual fees.",
    keywords: [
      "annual",
      "fee",
      "waiver",
      "waive",
      "waived",
      "free",
      "no fee",
      "low fee",
      "cheap",
      "affordable",
      "zero",
      "cost",
    ],
    trainingExamples: [
      "Any OCBC credit card without annual fees?",
      "Can I get fee waiver?",
      "Which card has the lowest fee?",
      "No annual fee card",
      "Fee waiver credit card",
      "Cheapest credit card",
      "Free credit card",
    ],
    templateResponse: {
      text: "You can review cards with low fees or waiver policies (subject to eligibility). Continue to the catalog to compare and apply.",
      buttons: [{ label: "Compare Cards", url: "https://www.ocbc.com/personal-banking/cards/card-comparison.page" }],
    },
  },
  {
    id: "students_first_card",
    name: "Students & first card (entry-level)",
    description:
      "Explore cards suitable for students/first-time cardholders subject to age and income eligibility.",
    keywords: [
      "student",
      "students",
      "first",
      "beginner",
      "entry",
      "level",
      "new",
      "young",
      "income",
      "minimum",
      "eligibility",
      "first-time",
      "fresh",
      "graduate",
    ],
    trainingExamples: [
      "Does OCBC have a student credit card?",
      "First credit card recommendations",
      "Minimum income for OCBC cards?",
      "Student credit card Singapore",
      "First time credit card",
      "Entry level card",
      "Card for fresh graduates",
    ],
    templateResponse: {
      text: "New to credit cards? Check age/income criteria first. If eligible, use the catalog to apply for an entry\u2011level card.",
      buttons: [{ label: "Apply for a Card", url: "https://www.ocbc.com/personal-banking/campaign/newcardpromo" }],
    },
  },
  {
    id: "family_kids",
    name: "Family & kids (groceries, utilities, education)",
    description:
      "Recommend cards aligned to family expenses: supermarkets, utilities, children-related spend.",
    keywords: [
      "family",
      "kids",
      "children",
      "child",
      "utilities",
      "education",
      "school",
      "parents",
      "household",
      "recurring",
      "bills",
      "family-friendly",
    ],
    trainingExamples: [
      "Best OCBC card for a family?",
      "Utilities and groceries—what should I get?",
      "Any perks for education fees?",
      "Family credit card",
      "Card for household expenses",
      "Card for utilities and groceries",
      "Card for parents",
    ],
    templateResponse: {
      text: "Families often benefit from grocery and utilities categories. Explore card options and apply via the catalog below.",
      buttons: [{ label: "View Family Cards", url: "https://www.ocbc.com/personal-banking/cards/365-cashback-credit-card" }],
    },
  },
  {
    id: "entertainment_subscriptions",
    name: "Entertainment & Subscriptions",
    description:
      "Focus on streaming, digital subscriptions, and entertainment merchants.",
    keywords: [
      "netflix",
      "spotify",
      "streaming",
      "subscription",
      "entertainment",
      "movie",
      "cinema",
      "digital",
      "youtube",
      "music",
      "platform",
      "disney",
      "apple",
    ],
    trainingExamples: [
      "Which OCBC card is good for Netflix/Spotify?",
      "Any bonus for online subscriptions?",
      "Movie tickets perks?",
      "Best card for streaming services",
      "Subscription cashback card",
      "Card for Netflix and Spotify",
      "Entertainment rewards card",
    ],
    templateResponse: {
      text: "Streaming and subscriptions can be rewarded on select cards (MCCs and caps apply). Compare and apply via the link below.",
      buttons: [{ label: "View Rewards Cards", url: "https://www.ocbc.com/personal-banking/cards/rewards-card" }],
    },
  },
  {
    id: "healthcare_insurance",
    name: "Healthcare & Insurance",
    description:
      "Purchases at clinics, hospitals, pharmacies; insurance premium payments where eligible.",
    keywords: [
      "healthcare",
      "health",
      "hospital",
      "clinic",
      "pharmacy",
      "medical",
      "insurance",
      "premium",
      "doctor",
      "medicine",
      "guardian",
      "watsons",
    ],
    trainingExamples: [
      "Do OCBC cards reward insurance premiums?",
      "Best card for pharmacy spend?",
      "Any medical bill benefits?",
      "Healthcare cashback card",
      "Insurance premium card rewards",
      "Card for medical expenses",
      "Pharmacy rewards card",
    ],
    templateResponse: {
      text: "Medical and insurance spends may have exclusions. Review card terms and eligible categories, then proceed to apply if suitable.",
      buttons: [{ label: "Great Eastern Cashflo Card", url: "https://www.ocbc.com/personal-banking/cards/great-eastern-cashflo-credit-card.page" }],
    },
  },
  {
    id: "overseas_fx",
    name: "Overseas Spend & FX",
    description:
      "Cards that reward overseas or foreign currency spend; considerations on FX fees.",
    keywords: [
      "overseas",
      "foreign",
      "currency",
      "fx",
      "exchange",
      "abroad",
      "international",
      "travel",
      "conversion",
      "foreign currency",
      "usd",
      "eur",
      "jpy",
    ],
    trainingExamples: [
      "Which OCBC card is best for overseas shopping?",
      "Any extra miles for foreign currency?",
      "What are the FX fees?",
      "Best card for overseas spending",
      "No FX fee credit card",
      "Card for international purchases",
      "Foreign currency cashback",
    ],
    templateResponse: {
      text: "If you spend in foreign currency, compare cards that reward overseas transactions and note FX fees. Use the link to view and apply.",
      buttons: [{ label: "View Travel Cards", url: "https://www.ocbc.com/personal-banking/cards/90-degrees-travel-credit-card" }],
    },
  },
  {
    id: "contactless_wallets",
    name: "Contactless & Mobile Wallets",
    description:
      "User prioritizes tap-and-go, Apple Pay/Google Pay/Samsung Pay support.",
    keywords: [
      "contactless",
      "apple pay",
      "google pay",
      "samsung pay",
      "tap",
      "nfc",
      "mobile",
      "wallet",
      "paywave",
      "paypass",
      "digital wallet",
    ],
    trainingExamples: [
      "Do OCBC cards support Apple Pay/Google Pay?",
      "Which card works best for contactless?",
      "Any extra rewards for mobile wallet payments?",
      "Apple Pay credit card",
      "Contactless payment card",
      "NFC-enabled card",
      "Card for tap and go",
    ],
    templateResponse: {
      text: "Most OCBC cards support contactless and mobile wallets. Check eligibility and any channel\u2011specific terms, then apply below.",
      buttons: [{ label: "Add Card to Mobile Wallet", url: "https://www.ocbc.com/personal-banking/help-and-support/cards/adding-card-to-mobile-wallet" }],
    },
  },
  {
    id: "supplementary_cards",
    name: "Supplementary Cards & Family Sharing",
    description:
      "For users wanting supplementary cards for spouse/children/parents.",
    keywords: [
      "supplementary",
      "supp",
      "additional",
      "family",
      "sharing",
      "spouse",
      "wife",
      "husband",
      "children",
      "parents",
      "secondary",
      "add-on",
    ],
    trainingExamples: [
      "How to get an OCBC supplementary card?",
      "Do supplementary spends earn rewards?",
      "Any age requirement for supplementary holders?",
      "Supplementary credit card",
      "Additional card for family member",
      "Spouse credit card",
      "Card for spouse and children",
    ],
    templateResponse: {
      text: "You can request supplementary cards after the primary card is approved. Start with the main card application from the catalog below.",
      buttons: [{ label: "Supplementary Card Info", url: "https://www.ocbc.com/personal-banking/help-and-support/cards/general" }],
    },
  },
  {
    id: "signup_promotions",
    name: "Sign-up Promotions & Welcome Gifts",
    description:
      "Help users discover current promotions for new-to-bank or existing customers.",
    keywords: [
      "promotion",
      "promo",
      "welcome",
      "gift",
      "sign-up",
      "signup",
      "new",
      "bonus",
      "offer",
      "deal",
      "reward",
      "cashback",
      "voucher",
      "free",
    ],
    trainingExamples: [
      "What are the latest OCBC credit card promos?",
      "Any welcome gift for new customers?",
      "Do I qualify for the sign-up bonus?",
      "Credit card promotions Singapore",
      "New card sign up bonus",
      "Welcome gift credit card",
      "Credit card offer",
    ],
    templateResponse: {
      text: "Welcome offers change periodically and have spend conditions. View current promos in the catalog and apply from there.",
      buttons: [{ label: "View Card Promotions", url: "https://www.ocbc.com/personal-banking/cards/card-promotions" }],
    },
  },
  {
    id: "eligibility_requirements",
    name: "Eligibility & Application Requirements",
    description:
      "Age, income, residency, and documentation required to apply for OCBC cards.",
    keywords: [
      "eligibility",
      "eligible",
      "income",
      "age",
      "residency",
      "foreigner",
      "singaporean",
      "pr",
      "documents",
      "nric",
      "apply",
      "requirements",
      "minimum",
      "criteria",
    ],
    trainingExamples: [
      "What is the minimum income for OCBC cards?",
      "Can foreigners apply?",
      "What documents do I need?",
      "Who can apply for OCBC credit card",
      "Income requirement credit card",
      "Credit card for foreigners Singapore",
      "How to apply for credit card",
    ],
    templateResponse: {
      text: "Age, income and residency criteria apply (per MAS/OCBC). Review requirements in the catalog and proceed to apply if eligible.",
      buttons: [{ label: "Apply for a Card", url: "https://www.ocbc.com/personal-banking/cards/credit-card" }],
    },
  },
  {
    id: "fees_charges",
    name: "Fees & Charges",
    description:
      "Annual fee, late payment fee, interest rates, cash advance fee, foreign transaction charges.",
    keywords: [
      "fee",
      "fees",
      "charges",
      "interest",
      "rate",
      "late",
      "payment",
      "cash advance",
      "annual",
      "foreign transaction",
      "penalty",
      "cost",
      "price",
    ],
    trainingExamples: [
      "What are the fees for OCBC credit cards?",
      "Interest rate and late fee?",
      "Any cash advance fees?",
      "Credit card interest rate",
      "Late payment fee",
      "Annual fee credit card",
      "Cash advance charges",
    ],
    templateResponse: {
      text: "Annual fees, late charges, interest and FX fees apply. Review the fee schedule in the catalog before you apply.",
      buttons: [{ label: "View Fees & Charges", url: "https://www.ocbc.com/assets/pdf/fees_charges.pdf" }],
    },
  },
  {
    id: "rewards_currency",
    name: "Rewards currency (points/miles/cashback)",
    description:
      "Explain how OCBC rewards work (e.g., points vs miles vs cashback) and redemption basics.",
    keywords: [
      "rewards",
      "points",
      "miles",
      "cashback",
      "redeem",
      "redemption",
      "earn",
      "credited",
      "expiry",
      "conversion",
      "accumulate",
      "transfer",
      "how",
      "work",
    ],
    trainingExamples: [
      "How do OCBC points work?",
      "Do OCBC cards earn miles directly?",
      "How is cashback credited?",
      "Difference between points miles and cashback",
      "How to redeem reward points",
      "OCBC rewards programme",
      "Points to miles conversion",
    ],
    templateResponse: {
      text: "OCBC cards earn cashback, miles or points depending on product and category. Compare how rewards are earned and credited, then apply.",
      buttons: [{ label: "View Rewards Card", url: "https://www.ocbc.com/personal-banking/cards/rewards-card" }],
    },
  },
  {
    id: "bill_payments_exclusions",
    name: "Bill Payments & Exclusions",
    description:
      "Identify which transactions may be excluded from rewards (e.g., government payments, education, top-ups).",
    keywords: [
      "bill",
      "bills",
      "exclusion",
      "exclusions",
      "excluded",
      "government",
      "gst",
      "tax",
      "insurance",
      "wallet",
      "top-up",
      "topup",
      "eligible",
      "earn",
    ],
    trainingExamples: [
      "Do I earn rewards on insurance/govt bills?",
      "Are wallet top-ups eligible?",
      "Any excluded categories?",
      "Which transactions don't earn rewards",
      "Government payment rewards",
      "Excluded from cashback",
      "Can I earn miles on bills",
    ],
    templateResponse: {
      text: "Some bill types (e.g., government, insurance, wallet top\u2011ups) may be excluded from rewards. Check exclusions, then apply if the card still fits.",
      buttons: [{ label: "Card Help & Support", url: "https://www.ocbc.com/personal-banking/help-and-support/cards/general" }],
    },
  },
  {
    id: "luxury_department_stores",
    name: "Luxury & Department Stores",
    description:
      "Cards suitable for premium retail and department store spending.",
    keywords: [
      "luxury",
      "premium",
      "department",
      "store",
      "shopping",
      "retail",
      "big-ticket",
      "isetan",
      "takashimaya",
      "gucci",
      "luxury goods",
      "high-end",
    ],
    trainingExamples: [
      "Best OCBC card for luxury shopping?",
      "Any perks for department stores?",
      "Which card helps for big-ticket retail?",
      "Premium shopping credit card",
      "Card for luxury brands",
      "Department store cashback",
      "High-end retail card",
    ],
    templateResponse: {
      text: "For premium retail spends, compare cards that fit large purchases (note monthly caps). Apply from the catalog below.",
      buttons: [{ label: "View VOYAGE Card", url: "https://www.ocbc.com/personal-banking/cards/voyage-credit-card.page" }],
    },
  },
  {
    id: "installment_plans",
    name: "Installment Plans (0% IPP)",
    description:
      "Discovery around merchants offering installment payment plans and implications on rewards.",
    keywords: [
      "installment",
      "instalment",
      "ipp",
      "0%",
      "interest-free",
      "split",
      "payment",
      "plan",
      "monthly",
      "tenure",
      "merchant",
      "defer",
    ],
    trainingExamples: [
      "Does OCBC offer 0% installment plans?",
      "Do I still earn rewards on installments?",
      "Any fees for IPP?",
      "Interest-free installment credit card",
      "0% payment plan",
      "Split payment option",
      "Pay by installments",
    ],
    templateResponse: {
      text: "Some merchants offer 0% IPP; rewards and fees may differ on installments. Review details in T&Cs and apply if it suits your needs.",
      buttons: [{ label: "View Instalment Plans", url: "https://www.ocbc.com/personal-banking/cards/card-services/interest-free-instalment-plans" }],
    },
  },
  {
    id: "card_design",
    name: "Card design & metal/plastic",
    description:
      "Preferences around card material/design and associated fees or tiers.",
    keywords: [
      "design",
      "metal",
      "plastic",
      "look",
      "appearance",
      "premium",
      "colour",
      "color",
      "limited edition",
      "exclusive",
      "tier",
      "material",
    ],
    trainingExamples: [
      "Does OCBC have a metal card?",
      "Are there premium designs?",
      "Any extra fee for special designs?",
      "Metal credit card Singapore",
      "Premium card design",
      "Exclusive card design",
      "OCBC titanium card",
    ],
    templateResponse: {
      text: "Designs vary by product/tier. Choose based on benefits first; then apply via the catalog.",
      buttons: [{ label: "View FRANK Card Designs", url: "https://www.ocbc.com/personal-banking/cards/ocbc-frank-credit-card" }],
    },
  },
  {
    id: "security_controls",
    name: "Security & Controls",
    description:
      "Card security features: transaction alerts, freezing card, spending controls, online limits.",
    keywords: [
      "lock",
      "freeze",
      "security",
      "alert",
      "notification",
      "control",
      "limit",
      "spending",
      "block",
      "virtual",
      "otp",
      "protect",
      "safe",
    ],
    trainingExamples: [
      "Can I lock my OCBC card?",
      "Are there spending limits/alerts?",
      "Virtual card numbers?",
      "Freeze credit card",
      "Set spending limit",
      "Transaction alert",
      "Card security features",
    ],
    templateResponse: {
      text: "Once you have a card, you can lock/unlock and set controls in\u2011app. To get started, apply for a card via the catalog below.",
      buttons: [{ label: "Card Services & Controls", url: "https://www.ocbc.com/personal-banking/help-and-support/cards/card-services" }],
    },
  },
  {
    id: "sustainability_esg",
    name: "Sustainability & ESG perks",
    description:
      "Discovery for environmentally conscious users (e.g., eco merchants, donations).",
    keywords: [
      "sustainability",
      "sustainable",
      "eco",
      "green",
      "environment",
      "esg",
      "donation",
      "charity",
      "carbon",
      "environmental",
      "ethical",
      "responsible",
    ],
    trainingExamples: [
      "Any OCBC card with eco benefits?",
      "Do I earn rewards on donations?",
      "Green merchant perks?",
      "Sustainable credit card",
      "Eco-friendly card",
      "ESG credit card",
      "Green rewards card",
    ],
    templateResponse: {
      text: "If you value eco\u2011friendly spending, check eligible categories and exclusions first. Compare cards and apply below.",
      buttons: [{ label: "OCBC Sustainability Hub", url: "https://www.ocbc.com/personal-banking/sustainability.page" }],
    },
  },
  {
    id: "existing_customer",
    name: "Existing Customer Optimization",
    description:
      "Users already holding OCBC cards wanting to optimize or add another complementary card.",
    keywords: [
      "existing",
      "already",
      "have",
      "another",
      "complementary",
      "maximize",
      "optimize",
      "second card",
      "additional",
      "improve",
      "upgrade",
      "better",
    ],
    trainingExamples: [
      "I have an OCBC card\u2014should I get another?",
      "Which card complements my current one?",
      "How to maximize my rewards?",
      "Already have OCBC card",
      "Complement existing card",
      "Second credit card",
      "Maximize credit card rewards",
    ],
    templateResponse: {
      text: "Already have an OCBC card? Consider a complementary card to cover other categories. Compare options in the catalog and apply.",
      buttons: [{ label: "Compare Cards", url: "https://www.ocbc.com/personal-banking/cards/card-comparison.page" }],
    },
  },
];

export const OUT_OF_SCOPE_INTENT: OutOfScopeIntent = {
  id: "out_of_scope",
  name: "Out of Scope",
  templateResponse: {
    text: "I'm sorry, I wasn't able to find a match for your query. I can help with OCBC credit card topics — try asking about card recommendations, rewards, fees, eligibility, or how to apply.",
    buttons: [
      { label: "Best credit card for me" },
      { label: "Cashback cards" },
      { label: "Travel miles cards" },
      { label: "How to apply" },
    ],
  },
};
